spring.application.name=library-management-system
server.port=8080

spring.thymeleaf.cache=false
spring.mvc.hiddenmethod.filter.enabled=true

firebase.project-id=${FIREBASE_PROJECT_ID:}
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:}

library.security.session-timeout-minutes=30
library.fine.free-days=7
library.fine.amount-per-day=5
library.issue.max-books-per-student=5

logging.level.com.library=INFO
logging.file.name=logs/library-management.log
